name: Second
on: push
jobs:
    job1: 
        name: first job
        runs-on: ubuntu-latest
        steps:
              - name: first step
                uses: actions/checkout@v2
              - name: step two
                run: echo Hello World!
    job2:
        name: second job
        runs-on: window-latest
        steps:
              - name: first step
                uses: actions/checkout@v2
              - name: step two
                run: echo Hello World!
    job3:
        name: third job
        runs-on: macos-latest
        steps:
              - name: first step
                uses: actions/checkout@v2
              - name: step two
                run: echo Hello World!
    job4:
        name: fourth job
        runs-on: window-latest
        steps:
              - name: first step
                uses: actions/checkout@v2
              - name: step two
                run: echo Hello World!
